---
- name: "Ensure tower-cli is available in Ansible Tower virtual environment"
  include_role:
    name: "ansible_tower_genie_virtual_environments"
  vars:
    tower_venv_pylibs:
      - "ansible-tower-cli"
    tower_venv_path:
      "/var/lib/awx/venv/ansible"
  delegate_to: "localhost"
  connection: "local"
  run_once: True
  when: 'discovered_host_install_prereqs'

- name: "Ensure {{ discovered_host_inventory_name }} exists in Ansible Tower"
  tower_inventory:
    tower_host: "{{ tower_url }}"
    tower_username: "{{ tower_user }}"
    tower_password: "{{ tower_pass }}"
    tower_verify_ssl: "{{ tower_verify_ssl }}"
    description: "{{ discovered_host_inventory_description }}"
    organization: "{{ tower_org }}"
    name: "{{ discovered_host_inventory_name }}"
    state: "present"
  delegate_to: "localhost"
  connection: "local"
  become: False

- name: "Ensure default inventory groups exists in Ansible Tower Inventory"
  tower_group:
    tower_username: "{{ tower_user }}"
    tower_password: "{{ tower_pass }}"
    tower_host: "{{ tower_url }}"
    tower_verify_ssl: "{{ tower_verify_ssl }}"
    name: "{{ item.name }}"
    description: "{{ item.desc }}"
    inventory: "{{ discovered_host_inventory_name }}"
    source: "manual"
    state: "present"
  with_items:
    - "{{ discovered_host_inventory_default_groups }}"
  delegate_to: "localhost"
  connection: "local"
  run_once: True
  become: False

- name: "Ensure discovered application inventory groups exist in Ansible Tower Inventory"
  tower_group:
    tower_username: "{{ tower_user }}"
    tower_password: "{{ tower_pass }}"
    tower_host: "{{ tower_url }}"
    tower_verify_ssl: "{{ tower_verify_ssl }}"
    name: "{{ item.name }}"
    description: "{{ item.desc | default(omit) }}"
    inventory: "{{ discovered_host_inventory_name }}"
    source: "manual"
    state: "present"
  with_items:
    - "{{ hostvars[inventory_hostname]['discovered_apps'] }}"
  when: "hostvars[inventory_hostname]['discovered_apps'] | length > 0"
  delegate_to: "localhost"
  connection: "local"
  become: False

- name: "Ensure discovered host exists in Ansible Tower inventory"
  tower_host:
    tower_username: "{{ tower_user }}"
    tower_password: "{{ tower_pass }}"
    tower_host: "{{ tower_url }}"
    tower_verify_ssl: "{{ tower_verify_ssl }}"
    name: "{{ ansible_fqdn }}"
    inventory: "{{ discovered_host_inventory_name }}"
    enabled: True
    variables:
      discovered_facts: "{{ ansible_facts }}"
    state: "present"
  delegate_to: "localhost"
  connection: "local"
  become: False
