---
- name: "Initialize signature scoring for {{ amf_as_discovered_app.name }}"
  set_fact:
    amf_as_svc_count: "0"
    amf_as_usr_count: "0"
    amf_as_grp_count: "0"
    amf_as_path_count: "0"
    amf_as_proc_count: "0"
    amf_as_pkg_count: "0"

- name: "Check for {{ amf_as_discovered_app.name }} services"
  set_fact:
    amf_as_svc_count: "{{ amf_as_svc_count | int + 1 }}"
  with_items: "{{ amf_as_services }}"
  when:
    - "ansible_facts['services'][service] is defined"
  loop_control:
    loop_var: "service"

- name: "Check if {{ amf_as_discovered_app.name }} user(s) exist"
  set_fact:
    amf_as_usr_count: "{{ amf_as_usr_count | int + 1 }}"
  with_items: "{{ amf_as_user_group.users }}"
  when:
    - 'item in ansible_facts | json_query("local_users[*].user")'

- name: "Check if {{ amf_as_discovered_app.name }} group(s) exist"
  set_fact:
    amf_as_grp_count: "{{ amf_as_grp_count | int + 1 }}"
  with_items: "{{ amf_as_user_group.groups }}"
  when:
    - 'item in ansible_facts | json_query("local_groups[*].group")'

- name: "Check if {{ amf_as_discovered_app.name }} application path(s) exist"
  include_tasks: "check_paths.yml"
  with_items: "{{ amf_as_paths }}"
  loop_control:
    loop_var: "path"

- name: "Check for {{ amf_as_discovered_app.name }} packages"
  set_fact:
    amf_as_pkg_count: "{{ amf_as_pkg_count | int + 1 }}"
  with_items: "{{ amf_as_packages }}"
  when: "ansible_facts['packages'][package] is defined"
  loop_control:
    loop_var: "package"

- name: "Set list of running commands"
  set_fact:
    proc_commands: "{{ ansible_facts | json_query('running_processes.processes[*].command') }}"

- name: "Debug proc_commands"
  debug:
    var: "proc_commands"
    verbosity: "1"

- name: "Check for {{ amf_as_discovered_app.name }} processes"
  set_fact:
    amf_as_proc_count: "{{ amf_as_proc_count | int + 1 }}"
  when: "item[0] in item[1]"
  with_nested:
      - "{{ amf_as_processes }}"
      - "{{ proc_commands }}"

- name: "Debug application signature scoring counters"
  debug:
    verbosity: "1"
    msg:
      - "amf_as_grp_count: {{ amf_as_grp_count | int }}"
      - "amf_as_path_count: {{ amf_as_path_count | int }}"
      - "amf_as_pkg_count: {{ amf_as_pkg_count | int }}"
      - "amf_as_proc_count: {{ amf_as_proc_count | int }}"
      - "amf_as_svc_count: {{ amf_as_svc_count | int }}"
      - "amf_as_usr_count: {{ amf_as_usr_count | int }}"

- name: "Identify application as {{ amf_as_discovered_app.name }}"
  set_fact:
    discovered_apps: "{{ discovered_apps | union([amf_as_discovered_app]) }}"

# Modify these counts to suit your identification needs
# Here's some examples of checking conditions
  when:
    - "amf_as_svc_count | int == 2"
    - "amf_as_usr_count | int >= 1"
    - "amf_as_grp_count | int >= 1"
    - "amf_as_path_count | int >= 1"
    - "amf_as_pkg_count | int == 1"
    - "amf_as_proc_count | int >= 1"
