---
- name: "Build coalmine SQL"
  template:
    src: "seed_coalmine.sql.j2"
    dest: "{{ pg_home }}/seed_coalmine.sql"
    mode: "0600"
    group: "{{ pg_group }}"
    owner: "{{ pg_user }}"
  delegate_to: "{{ amf_webservice_host }}"
  run_once: True
  notify:
    - "Seed postgresql"
