---
- name: "Ansible Migration Factory - Report"
  hosts: "all"
  gather_facts: False
  tasks:
    - name: "Generate report"
      block:
        - name: "Ensure report directory exists"
          file:
            state: "directory"
            path: "/root/reports"
            mode: "0755"
            owner: "root"
            group: "root"
          connection: "local"
          become: True

        - name: "Create report"
          template:
            src: "simple_report.csv.j2"
            dest: "/root/reports/simple_report.csv"
            owner: "root"
            group: "root"
            mode: "0644"
          connection: "local"
          become: True
      delegate_to: "localhost"
      run_once: True
