---
- name: "amf-discovery-cron-jobs"
  src: "https://ahuffman:qyKfZyb5D8ytmEBeFskv@gitlab.consulting.redhat.com/Canary/ansible-canary-role-discovery-cron-jobs.git"
  version: "master"
  scm: "git"
- name: "amf-discovery-litening-ports"
  src: "https://ahuffman:qyKfZyb5D8ytmEBeFskv@gitlab.consulting.redhat.com/Canary/ansible-canary-role-discovery-listening-ports.git"
  version: "master"
  scm: "git"
- name: "amf-discovery-user-group"
  src: "https://ahuffman:qyKfZyb5D8ytmEBeFskv@gitlab.consulting.redhat.com/Canary/ansible-canary-role-discovery-user-group.git"
  version: "master"
  scm: "git"
- name: "amf-discovery-processes"
  src: "https://ahuffman:qyKfZyb5D8ytmEBeFskv@gitlab.consulting.redhat.com/Canary/ansible-canary-role-discovery-processes.git"
  version: "master"
  scm: "git"
- name: "amf-yum-repos"
  src: "https://ahuffman:qyKfZyb5D8ytmEBeFskv@gitlab.consulting.redhat.com/Canary/ansible-canary-role-discovery-yum-repos.git"
  version: "master"
  scm: "git"
