---
- name: "Generate Discovery Report"
  hosts: "localhost"
  gather_facts: False
  connection: "local"
  vars_files:
    - "vars/report.yml"
  tasks:
    - name: "Generate Report"
      block:
        - name: "Ensure markdown converter is installed"
          package:
            name: "discount"
            state: "installed"

        - name: "Create report"
          template:
            src: "discovery_report.md.j2"
            dest: "{{ rpt_base_path }}/discovery_report.md"
            owner: "{{ rpt_owner }}"
            group: "{{ rpt_group }}"
            mode: "{{ rpt_mode }}"

        - name: "Convert report to html"
          command: "markdown -f githubtags -f fencedcode -f toc -T -o {{ rpt_base_path}}/index.html {{ rpt_base_path }}/discovery_report.md"

        - name: "Ensure proper report permissions"
          file:
            path: "/usr/share/nginx/html/index.html"
            owner: "{{ rpt_owner }}"
            group: "{{ rpt_group }}"
            mode: "{{ rpt_mode }}"
            state: "file"
      delegate_to: "{{ discovery_report_server }}"
