---
- name: "Generate Discovery Report"
  hosts: "all"
  gather_facts: False
  vars_files:
    - "../vars/discovery_vars.yml"
  tasks:
    - name: "Generate Discovery Report"
      block:
        - name: "Ensure report directory exists"
          file:
            state: "directory"
            path: "/home/awx/reports"
            mode: "0755"
            owner: "awx"
            group: "awx"
          connection: "local"

        - name: "Create report"
          template:
            src: "../templates/discovery_report.md.j2"
            dest: "/home/awx/reports/discovery_report.md"
            owner: "awx"
            group: "awx"
            mode: "0755"
          connection: "local"

        - name: "Copy report to {{ discovery_report_server }}"
          command: "scp /home/awx/reports/discovery_report.md root@{{ discovery_report_server }}:/var/www/html/"
          connection: "local"
      delegate_to: "localhost"
      run_once: True
