---
- name: "Ansible Migration Factory - Report"
  hosts: "all"
  gather_facts: False
  tasks:
    - name: "Generate report"
      block:
        - name: "Ensure report directory exists"
          file:
            state: "directory"
            path: "/home/awx/reports"
            mode: "0755"
            owner: "awx"
            group: "awx"
          connection: "local"

        - name: "Create report"
          template:
            src: "../templates/resource_report.csv.j2"
            dest: "/home/awx/reports/resource_report.csv"
            owner: "awx"
            group: "awx"
            mode: "0644"
          connection: "local"
      delegate_to: "localhost"
      run_once: True
