---
- name: "Ansible Migration Factory - Report"
  hosts: "localhost"
  gather_facts: False
  connection: "local"
  vars_files:
    - "../vars/discovery_vars.yml"
  tasks:
    - name: "Create report"
      template:
        src: "../templates/resource_report.csv.j2"
        dest: "/var/www/html/resource_report.csv"
        owner: "root"
        group: "root"
        mode: "0755"
      delegate_to: "{{ discovery_report_server }}"
