---
# tasks file for rpmdiff

#Get yum repolist, remove column headers and last line that gives sum.
# Remove the head portion to make work with dnf command
- name: "Enterprise Linux"
  block:
    - name: "get repolist"
      shell: 'yum repolist all | head -n -1'
      args:
        warn: False
      register: repoList
      changed_when: false

    - name: "Convert repolist output to Json"
      repolist:
        repolist: "{{ repoList.stdout_lines | to_json }}"
  when: "ansible_os_family == 'RedHat'"

# repolist returns ansible_facts['yum_repo_list'] json
