---
amf_as_services: []

amf_as_user_group:
  users: []
  groups: []

amf_as_paths:
  - "/etc/oratab"
  - "/etc/oraInst.loc"

amf_as_packages: []


amf_as_processes:
  - "asm_mmon_"
  - "asm_pmon_"
  - "asm_smon_"

# Returned fields
amf_as_discovered_app:
  name: "Oracle Automatic Storage Management"
  desc: "Hosts identified as Oracle Automatic Storage Management (ASM) Servers"
