---
- name: "Ensure netstat is available on RHEL"
  package:
    name: "net-tools"
    state: "installed"
  become: True
  when: 'ansible_os_family == "RedHat"'

- name: "Collect netstat facts"
  listen_ports_facts:

# listener module returns ansible_facts['tcp_listen'] and ansible_facts['udp_listen'] json
