---
- name: "Enterprise Linux"
  block:
    - name: "Ensure netstat is available on RHEL"
      package:
        name: "net-tools"
        state: "installed"
      become: True

    - name: "Collect netstat facts"
      listen_ports_facts:
  when: 'ansible_os_family == "RedHat"'

# listener module returns ansible_facts['tcp_listen'] and ansible_facts['udp_listen'] json
