---
- name: "Build Custom Facts"
  set_fact:
    custom_facts_formatted:
      - "{{ sudoers }}"
      - "{{ local_users }}"
      - "{{ local_groups }}"
      - "{{ listeners }}"
      - "{{ processes }}"
      - "{{ yum_repo_list }}"
      - "{{ cron_jobs }}"
    facts_formatted:
      - "{{ ansible_facts }}"
      - "{{ packages }}"
      - "{{ services }}"

- name: "Ensure data is prepared for Coalmine"
  convertWebService:
    ansible_facts: "{{ facts_formatted }}"
    parent_app_name: "Unknown Application"
    hostname: "{{ inventory_hostname }}"
    custom_facts_list: '{{ custom_facts_formatted }}'
  register: "coalmine_data"

- debug:
    var: "coalmine_data"
