---
- name: "Build custom facts"
  set_fact:
    custom_facts_formatted:
      - {sudoers: {{ sudoers }}}
      - {local_users: {{ local_users }}}
      - {local_groups: {{ local_groups }}}
      - {listeners: {{ listeners }}}
      - {processes: {{ processes }}}
      - {yum_repo_list: {{ yum_repo_list }}}
      - {cron_jobs: {{ cron_jobs }}}

- debug:
    var: "custom_facts_formatted"

- name: "Ensure data is prepared for Coalmine"
  convertWebService:
    ansible_facts: "{{ ansible_facts }}"
    parent_app_name: "Unknown Application"
    hostname: "{{ inventory_hostname }}"
    custom_facts_list: "{{ custom_facts_formatted }}"
  register: "coalmine_data"

- debug:
    var: "coalmine_data"
