---
amf_as_services: []

amf_as_user_group:
  users: []
  groups: []

amf_as_paths: []

amf_as_packages: []


amf_as_processes:
  - "com.ibm.wmqfte.agent.Agent"

# Returned fields
amf_as_discovered_app:
  name: "IBM WebSphere MQ File Transfer Edition"
  desc: "Hosts identified as IBM WebSphere MQ File Transfer Edition Servers"
